// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Light-ink-yht/admin-hub/internal/repository/cache/code_cache"
	"github.com/Light-ink-yht/admin-hub/internal/repository/code_repo"
	"github.com/Light-ink-yht/admin-hub/internal/repository/dao"
	"github.com/Light-ink-yht/admin-hub/internal/repository/log_repo"
	"github.com/Light-ink-yht/admin-hub/internal/service/code_svc"
	"github.com/Light-ink-yht/admin-hub/internal/service/log_svc"
	"github.com/Light-ink-yht/admin-hub/internal/web/user_web"
	"github.com/Light-ink-yht/admin-hub/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitWebServer 初始化 Web 服务器
func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	codeCache := code_cache.NewCodeCache(cmdable)
	db := ioc.InitDB()
	codeDAO := dao.NewCodeDAO(db)
	codeRepository := code_repo.NewCodeRepository(codeCache, codeDAO)
	logRepository := log_repo.NewLogRepository(db)
	logger := ioc.InitLogger(db)
	logService := log_svc.NewLogService(logRepository, logger)
	emailServiceFace := code_svc.NewEmailService(codeRepository, logService)
	userHandler := user_web.NewUserHandler(emailServiceFace, logService)
	engine := ioc.InitWebServer(userHandler, cmdable, logService, logger)
	return engine
}
