// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Light-ink-yht/admin-hub/internal/repository/cache/code_cache"
	"github.com/Light-ink-yht/admin-hub/internal/repository/code_repo"
	"github.com/Light-ink-yht/admin-hub/internal/repository/dao"
	"github.com/Light-ink-yht/admin-hub/internal/repository/email_repo"
	"github.com/Light-ink-yht/admin-hub/internal/repository/log_repo"
	"github.com/Light-ink-yht/admin-hub/internal/repository/sms_repo"
	"github.com/Light-ink-yht/admin-hub/internal/repository/user_repo"
	"github.com/Light-ink-yht/admin-hub/internal/service/code_svc"
	"github.com/Light-ink-yht/admin-hub/internal/service/email_svc"
	"github.com/Light-ink-yht/admin-hub/internal/service/log_svc"
	"github.com/Light-ink-yht/admin-hub/internal/service/sms_svc"
	"github.com/Light-ink-yht/admin-hub/internal/service/user_svc"
	"github.com/Light-ink-yht/admin-hub/internal/web/email_web"
	"github.com/Light-ink-yht/admin-hub/internal/web/sms_web"
	"github.com/Light-ink-yht/admin-hub/internal/web/user_web"
	"github.com/Light-ink-yht/admin-hub/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitWebServer 初始化 Web 服务器
func InitWebServer() *gin.Engine {
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userRepo := user_repo.NewUserRepo(userDao)
	userService := user_svc.NewUserService(userRepo)
	cmdable := ioc.InitRedis()
	codeCache := code_cache.NewCodeCache(cmdable)
	codeDAO := dao.NewCodeDAO(db)
	codeRepository := code_repo.NewCodeRepository(codeCache, codeDAO)
	logRepository := log_repo.NewLogRepository(db)
	logger := ioc.InitLogger(db)
	logService := log_svc.NewLogService(logRepository, logger)
	emailConfigDAO := dao.NewEmailConfigDAO(db)
	emailConfigRepository := email_repo.NewEmailConfigRepository(emailConfigDAO)
	emailTemplateDAO := dao.NewEmailTemplateDAO(db)
	emailTemplateRepository := email_repo.NewEmailTemplateRepository(emailTemplateDAO)
	emailServiceFace := code_svc.NewEmailService(codeRepository, logService, emailConfigRepository, emailTemplateRepository)
	smsConfigDAO := dao.NewSmsConfigDAO(db)
	smsConfigRepository := sms_repo.NewSmsConfigRepository(smsConfigDAO)
	smsTemplateRepository := sms_repo.NewSmsTemplateRepository(smsConfigDAO)
	smsServiceFace := code_svc.NewSmsService(codeRepository, logService, smsConfigRepository, smsTemplateRepository)
	userHandler := user_web.NewUserHandler(userService, emailServiceFace, smsServiceFace, logService)
	emailService := email_svc.NewEmailService(emailConfigRepository, emailTemplateRepository)
	emailHandler := email_web.NewEmailHandler(emailService, logService)
	service := sms_svc.NewSmsService(smsConfigRepository, smsTemplateRepository, logService)
	smsHandler := sms_web.NewSmsHandler(service, logService)
	engine := ioc.InitWebServer(userHandler, emailHandler, smsHandler, cmdable, logService, logger)
	return engine
}
