// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Light-ink-yht/admin-hub/internal/repository/cache/code_cache"
	"github.com/Light-ink-yht/admin-hub/internal/repository/code_repo"
	"github.com/Light-ink-yht/admin-hub/internal/service/code_svc"
	"github.com/Light-ink-yht/admin-hub/internal/web/user_web"
	"github.com/Light-ink-yht/admin-hub/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitWebServer 初始化 Web 服务器
func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	v := ioc.InitMiddlewares(cmdable)
	codeCache := code_cache.NewCodeCache(cmdable)
	codeRepository := code_repo.NewCodeRepository(codeCache)
	db := ioc.InitDB()
	logger := ioc.InitLogger(db)
	emailServiceFace := code_svc.NewEmailService(codeRepository, logger)
	userHandler := user_web.NewUserHandler(emailServiceFace)
	engine := ioc.InitWebServer(v, userHandler)
	return engine
}
