-- =================================================================================
-- 用户表 AA01
-- 用途：存储系统用户的基本信息，支持用户注册、登录、个人资料管理等功能
-- =================================================================================
CREATE TABLE IF NOT EXISTS AA01 (
    -- 基础字段（所有表共用）
    LAN001 BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    LAN002 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    LAN003 DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    LAN004 DATETIME COMMENT '删除时间',
    LAN005 VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '是否删除 1 否，2 是',
    LAN006 BIGINT NOT NULL DEFAULT 0 COMMENT '创建人',
    LAN007 BIGINT NOT NULL DEFAULT 0 COMMENT '修改人',
    
    -- 用户特有字段
    AAA001 BIGINT NOT NULL COMMENT '用户ID（业务主键）',
    AAA002 VARCHAR(100) NOT NULL COMMENT '邮箱 全局唯一',
    AAA003 VARCHAR(20) NOT NULL COMMENT '手机号 全局唯一',
    AAA004 VARCHAR(255) NOT NULL COMMENT '密码（加密存储）',
    AAA005 VARCHAR(50) COMMENT '昵称',
    AAA006 VARCHAR(50) COMMENT '真实姓名',
    AAA007 VARCHAR(255) COMMENT '头像URL',
    AAA008 VARCHAR(1) COMMENT '性别 1 男，2 女，3 未知',
    AAA009 DATE COMMENT '生日',
    AAA010 VARCHAR(1) NOT NULL DEFAULT '1' COMMENT '状态 1 启用，2 禁用',
    AAA011 VARCHAR(255) COMMENT '备注信息',
    AAA012 INT DEFAULT 0 COMMENT '登录次数',
    AAA013 DATETIME COMMENT '最后登录时间',
    AAA014 VARCHAR(50) COMMENT '最后登录IP地址',
    AAA015 DATETIME COMMENT '密码最后修改时间',
    
    -- 索引定义
    INDEX IDX_AAA001 (AAA001) COMMENT '按用户ID查询索引',
    UNIQUE INDEX IDX_UQ_AAA002 (AAA002) COMMENT '邮箱唯一索引',
    UNIQUE INDEX IDX_UQ_AAA003 (AAA003) COMMENT '手机号唯一索引',
    INDEX IDX_AAA010 (AAA010) COMMENT '按用户状态查询索引',
    INDEX IDX_LAN002 (LAN002) COMMENT '按创建时间查询索引',
    INDEX IDX_AAA013 (AAA013) COMMENT '按最后登录时间查询索引',
    INDEX IDX_AAA015 (AAA015) COMMENT '按密码修改时间查询索引',
    INDEX IDX_AAA005 (AAA005) COMMENT '按昵称查询索引',
    INDEX IDX_AAA006 (AAA006) COMMENT '按真实姓名查询索引',
    INDEX IDX_AAA010_AAA013 (AAA010, AAA013) COMMENT '按状态和最后登录时间组合查询索引',
    INDEX IDX_LAN002_AAA010 (LAN002, AAA010) COMMENT '按创建时间和状态组合查询索引'
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';